git_url: https://github.com/rahulkj/lightweightbox
git_branch: main
docker_hub_repository: rjain/lightweightbox

internal_registry:
  host: ((harbor_host))
  username: ((harbor_credentials.username))
  password: ((harbor_credentials.password))