---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: schedule
      trigger: true
    - get: git-repo
      trigger: true
  - in_parallel:
    - put: docker-image
      params:
        build: git-repo/ci
    - put: internal-registry
      params:
        build: git-repo/ci

resources:
- name: schedule
  type: time
  icon: camera-timer
  source:
    interval: 24h
    start: "12:20 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: git-repo
  type: git
  icon: github
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_credentials.username))
    password: ((git_credentials.password))

- name: docker-image
  type: docker-image
  icon: docker
  source:
    email: ((docker_hub_email))
    username: ((docker_hub_credentials.username))
    password: ((docker_hub_credentials.password))
    repository: ((docker_hub_repository))

- name: internal-registry
  type: docker-image
  icon: docker
  source:
    repository: ((internal_registry.host))/((docker_hub_repository))
    username: ((internal_registry.username))
    password: ((internal_registry.password))
    insecure_registries: 
    - ((internal_registry.host))
    - ((internal_registry.host)):443